apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-url
  namespace: flux-system
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA2UVo5UEhDL0IwMkRMNDBGTk1EL3J3bjB4ZDlCaWNHRm1nUjdxaTh2RURZNQ==
